package main

import (
	"encoding/base64"
	"fmt"
	"os"
	"strings"
	"text/template"

	jsoniter "github.com/json-iterator/go"
	"github.com/pkg/errors"
)

func main() {
	vmessList := []VmessInfo{}
	for _, vmessUrl := range vmessUrls {
		vmess, err := parseVmessUrl(vmessUrl)
		if err != nil {
			fmt.Printf("error: %v", err)
		} else {
			vmessList = append(vmessList, vmess)
			tpl := template.New("outbound")
			tpl = template.Must(tpl.Parse(tplString))

			if err := tpl.Execute(os.Stdout, vmessList); err != nil {
				fmt.Println(err)
				os.Exit(1)
			}

		}
	}
}

func parseVmessUrl(vmessUrl string) (VmessInfo, error) {
	var json = jsoniter.ConfigCompatibleWithStandardLibrary
	if len(vmessUrl) <= 0 {
		return VmessInfo{}, errors.New("Empty vmess URL string")
	}
	if !strings.HasPrefix(vmessUrl, "vmess://") {
		return VmessInfo{}, errors.New("Invalid vmess URL string")
	}
	vmDec, err := base64.StdEncoding.DecodeString(vmessUrl[8:])
	if err != nil && len(vmDec) > 0 {
		return VmessInfo{}, errors.Wrap(err, "Decode failed with vmess URL content")
	}
	var vmObj VmessInfo
	err = json.Unmarshal(vmDec, &vmObj)
	if err != nil {
		return VmessInfo{}, errors.Wrap(err, "Decode json failed")
	}
	return vmObj, nil
}

var tplString = `{{range .}}{
    "sendThrough" : "0.0.0.0",
    "mux" : {
      "enabled" : false,
      "concurrency" : 8
    },
    "protocol" : "vmess",
    "settings" : {
      "vnext" : [
        {
          "address" : "{{.Add}}",
          "users" : [
            {
              "id" : "3c91d857-2d40-39b9-81c0-f6adde8037ff",
              "alterId" : 2,
              "security" : "auto",
              "level" : 0
            }
          ],
          "port" : {{.Port}}
        }
      ]
    },
    "tag" : "{{.Ps}}",
    "streamSettings" : {
      "wsSettings" : {
        "path" : "\{{.Path}}",
        "headers" : {
          "Host" : "{{.Host}}"
        }
      },
      "quicSettings" : {
        "key" : "",
        "header" : {
          "type" : "none"
        },
        "security" : "none"
      },
      "tlsSettings" : {
        "allowInsecure" : false,
        "alpn" : [
          "http\/1.1"
        ],
        "serverName" : "{{.Add}}",
        "allowInsecureCiphers" : false
      },
      "sockopt" : {

      },
      "httpSettings" : {
        "path" : "",
        "host" : [
          ""
        ]
      },
      "tcpSettings" : {
        "header" : {
          "type" : "none"
        }
      },
      "kcpSettings" : {
        "header" : {
          "type" : "none"
        },
        "mtu" : 1350,
        "congestion" : false,
        "tti" : 20,
        "uplinkCapacity" : 5,
        "writeBufferSize" : 1,
        "readBufferSize" : 1,
        "downlinkCapacity" : 20
      },
      "security" : "tls",
      "network" : "ws"
    }
  }
  {{end}}`

var vmessUrls = []string{
	"vmess://eyJob3N0IjoidjJydS5kb3VibGVkb3Uud2luIiwicGF0aCI6IlwvZG91ZG91IiwidGxzIjoidGxzIiwiYWRkIjoidjJydS5kb3VibGVkb3Uud2luIiwicG9ydCI6NDQzLCJhaWQiOjIsIm5ldCI6IndzIiwidHlwZSI6Im5vbmUiLCJ2IjoiMiIsInBzIjoi4pGgVjLkv4TnvZfmlq/kvK/lipvimIAiLCJpZCI6IjNjOTFkODU3LTJkNDAtMzliOS04MWMwLWY2YWRkZTgwMzdmZiJ9",
	"vmess://eyJob3N0IjoidjJydS5kb3VibGVkb3Uud2luIiwicGF0aCI6IlwvZG91ZG91IiwidGxzIjoidGxzIiwiYWRkIjoic2hhbmdoYWkuZG91YmxlZG91LndpbiIsInBvcnQiOjUwMDA2LCJhaWQiOjIsIm5ldCI6IndzIiwidHlwZSI6Im5vbmUiLCJ2IjoiMiIsInBzIjoi4pGgVjLkv4TnvZfmlq/nlLXkv6Hnp7vliqjkvJjljJbimIAiLCJpZCI6IjNjOTFkODU3LTJkNDAtMzliOS04MWMwLWY2YWRkZTgwMzdmZiJ9",
	"vmess://eyJob3N0IjoiaGtkYWppLmRvdWJsZWRvdS53aW4iLCJwYXRoIjoiXC92MnJheSIsInRscyI6InRscyIsImFkZCI6ImhrZGFqaS5kb3VibGVkb3Uud2luIiwicG9ydCI6NDQzLCJhaWQiOjIsIm5ldCI6IndzIiwidHlwZSI6Im5vbmUiLCJ2IjoiMiIsInBzIjoi4pGgVjLlj7Dmub4y4piAIiwiaWQiOiIzYzkxZDg1Ny0yZDQwLTM5YjktODFjMC1mNmFkZGU4MDM3ZmYifQ==",
	"vmess://eyJob3N0IjoidjJ0dy5kb3VibGVkb3Uud2luIiwicGF0aCI6IlwvZG91ZG91IiwidGxzIjoidGxzIiwiYWRkIjoidjJ0dy5kb3VibGVkb3Uud2luIiwicG9ydCI6NDQzLCJhaWQiOjIsIm5ldCI6IndzIiwidHlwZSI6Im5vbmUiLCJ2IjoiMiIsInBzIjoi4pGgVjLlj7Dmub7imIAiLCJpZCI6IjNjOTFkODU3LTJkNDAtMzliOS04MWMwLWY2YWRkZTgwMzdmZiJ9",
	"vmess://eyJob3N0IjoiaGtkYWppLmRvdWJsZWRvdS53aW4iLCJwYXRoIjoiXC92MnJheSIsInRscyI6InRscyIsImFkZCI6Imh1bmFuLmRvdWJsZWRvdS53aW4iLCJwb3J0IjoyMDAzMywiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKRoFYy5Y+w5rm+57uPQ04y5Lit6L2sMuKYgCIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0IjoidjJ0dy5kb3VibGVkb3Uud2luIiwicGF0aCI6IlwvZG91ZG91IiwidGxzIjoidGxzIiwiYWRkIjoiaHVuYW4uZG91YmxlZG91LndpbiIsInBvcnQiOjUwMDA1LCJhaWQiOjIsIm5ldCI6IndzIiwidHlwZSI6Im5vbmUiLCJ2IjoiMiIsInBzIjoi4pGgVjLlj7Dmub7nu49DTjLkuK3ovazimIAiLCJpZCI6IjNjOTFkODU3LTJkNDAtMzliOS04MWMwLWY2YWRkZTgwMzdmZiJ9",
	"vmess://eyJob3N0IjoiZ2VydjIuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL3YycmF5IiwidGxzIjoidGxzIiwiYWRkIjoiZ3p5ZC5kb3VibGVkb3Uud2luIiwicG9ydCI6MjAwNDQsImFpZCI6MiwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsInYiOiIyIiwicHMiOiLikaBWMuW+t+WbveS8mOWMluKYgCIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0Ijoic3lkbmV5LmRvdWJsZWRvdS53aW4iLCJwYXRoIjoiXC9kb3Vkb3UiLCJ0bHMiOiJ0bHMiLCJhZGQiOiJnenlkLmRvdWJsZWRvdS53aW4iLCJwb3J0IjoyMzMzNiwiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKRoFYy5oKJ5bC85LyY5YyW4piAIiwiaWQiOiIzYzkxZDg1Ny0yZDQwLTM5YjktODFjMC1mNmFkZGU4MDM3ZmYifQ==",
	"vmess://eyJob3N0IjoidjJvbmVzZ3AuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL3YycmF5IiwidGxzIjoidGxzIiwiYWRkIjoiZ3p5ZC5kb3VibGVkb3Uud2luIiwicG9ydCI6MjMzMzUsImFpZCI6MiwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsInYiOiIyIiwicHMiOiLikaBWMuaWsOWKoOWdoTHimIAiLCJpZCI6IjNjOTFkODU3LTJkNDAtMzliOS04MWMwLWY2YWRkZTgwMzdmZiJ9",
	"vmess://eyJob3N0IjoiYW5vc2dwLmRvdWJsZWRvdS53aW4iLCJwYXRoIjoiXC9kb3Vkb3UiLCJ0bHMiOiJ0bHMiLCJhZGQiOiJhbm9zZ3AuZG91YmxlZG91LndpbiIsInBvcnQiOjIxMDAxLCJhaWQiOjAsIm5ldCI6IndzIiwidHlwZSI6Im5vbmUiLCJ2IjoiMiIsInBzIjoi4pGgVjLmlrDliqDlnaEz4piAIiwiaWQiOiIzYzkxZDg1Ny0yZDQwLTM5YjktODFjMC1mNmFkZGU4MDM3ZmYifQ==",
	"vmess://eyJob3N0IjoiYW5vc2dwLmRvdWJsZWRvdS53aW4iLCJwYXRoIjoiXC9kb3Vkb3UiLCJ0bHMiOiJ0bHMiLCJhZGQiOiJnenlkLmRvdWJsZWRvdS53aW4iLCJwb3J0IjoyMzM0MiwiYWlkIjowLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKRoFYy5paw5Yqg5Z2hNOKYgCIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0IjoidjIuMS5kb3VibGVkb3Uud2luIiwicGF0aCI6IlwvdjJyYXkiLCJ0bHMiOiJ0bHMiLCJhZGQiOiJ2Mi4xLmRvdWJsZWRvdS53aW4iLCJwb3J0Ijo4MCwiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKRoFYy5pel5pysMeKYgCIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0IjoidjIuMi5kb3VibGVkb3Uud2luIiwicGF0aCI6IlwvdjJyYXkiLCJ0bHMiOiJ0bHMiLCJhZGQiOiJ2Mi4yLmRvdWJsZWRvdS53aW4iLCJwb3J0Ijo4MCwiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKRoFYy5pel5pysMuKYgCIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0IjoidjIuMi5kb3VibGVkb3Uud2luIiwicGF0aCI6IlwvdjJyYXkiLCJ0bHMiOiJ0bHMiLCJhZGQiOiJzaGFuZ2hhaS5kb3VibGVkb3Uud2luIiwicG9ydCI6NTAwMDAsImFpZCI6MiwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsInYiOiIyIiwicHMiOiLikaBWMuaXpeacrDPnlLXkv6Hnp7vliqjkvJjljJbimIAiLCJpZCI6IjNjOTFkODU3LTJkNDAtMzliOS04MWMwLWY2YWRkZTgwMzdmZiJ9",
	"vmess://eyJob3N0IjoidjIuNC5kb3VibGVkb3Uud2luIiwicGF0aCI6IlwvdjJyYXkiLCJ0bHMiOiJ0bHMiLCJhZGQiOiJ2Mi40LmRvdWJsZWRvdS53aW4iLCJwb3J0Ijo0NDMsImFpZCI6MiwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsInYiOiIyIiwicHMiOiLikaBWMuaXpeacrDTimIAiLCJpZCI6IjNjOTFkODU3LTJkNDAtMzliOS04MWMwLWY2YWRkZTgwMzdmZiJ9",
	"vmess://eyJob3N0IjoidjIuNS5kb3VibGVkb3Uud2luIiwicGF0aCI6IlwvdjJyYXkiLCJ0bHMiOiJ0bHMiLCJhZGQiOiJ2Mi41LmRvdWJsZWRvdS53aW4iLCJwb3J0Ijo0NDMsImFpZCI6MiwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsInYiOiIyIiwicHMiOiLikaBWMuaXpeacrDXimIAiLCJpZCI6IjNjOTFkODU3LTJkNDAtMzliOS04MWMwLWY2YWRkZTgwMzdmZiJ9",
	"vmess://eyJob3N0IjoidjIuNC5kb3VibGVkb3Uud2luIiwicGF0aCI6IlwvdjJyYXkiLCJ0bHMiOiJ0bHMiLCJhZGQiOiJzaGFuZ2hhaS5kb3VibGVkb3Uud2luIiwicG9ydCI6NTAwMDEsImFpZCI6MiwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsInYiOiIyIiwicHMiOiLikaBWMuaXpeacrDbnlLXkv6Hnp7vliqjkvJjljJbimIAiLCJpZCI6IjNjOTFkODU3LTJkNDAtMzliOS04MWMwLWY2YWRkZTgwMzdmZiJ9",
	"vmess://eyJob3N0IjoidjIuNS5kb3VibGVkb3Uud2luIiwicGF0aCI6IlwvdjJyYXkiLCJ0bHMiOiJ0bHMiLCJhZGQiOiJzaGFuZ2hhaS5kb3VibGVkb3Uud2luIiwicG9ydCI6NTAwMDMsImFpZCI6MiwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsInYiOiIyIiwicHMiOiLikaBWMuaXpeacrDfnlLXkv6Hnp7vliqjkvJjljJbimIAiLCJpZCI6IjNjOTFkODU3LTJkNDAtMzliOS04MWMwLWY2YWRkZTgwMzdmZiJ9",
	"vmess://eyJob3N0IjoiY2VyYXVzLmRvdWJsZWRvdS53aW4iLCJwYXRoIjoiXC9kb3Vkb3UiLCJ0bHMiOiJ0bHMiLCJhZGQiOiJjZXJhdXMuZG91YmxlZG91LndpbiIsInBvcnQiOjQ0MywiYWlkIjowLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKRoFYy576O6KW/Q2VyYeKYgCIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0IjoiY2VyYXVzLmRvdWJsZWRvdS53aW4iLCJwYXRoIjoiXC9kb3Vkb3UiLCJ0bHMiOiJ0bHMiLCJhZGQiOiJzaGFuZ2hhaS5kb3VibGVkb3Uud2luIiwicG9ydCI6NTAwMDksImFpZCI6MCwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsInYiOiIyIiwicHMiOiLikaBWMue+juilv0NlcmHnlLXkv6HkvJjljJbimIAiLCJpZCI6IjNjOTFkODU3LTJkNDAtMzliOS04MWMwLWY2YWRkZTgwMzdmZiJ9",
	"vmess://eyJob3N0IjoidjJsb3NkbWl0MS5kb3VibGVkb3Uud2luIiwicGF0aCI6IlwvdjJyYXkiLCJ0bHMiOiJ0bHMiLCJhZGQiOiJ2Mmxvc2RtaXQxLmRvdWJsZWRvdS53aW4iLCJwb3J0Ijo0NDMsImFpZCI6MiwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsInYiOiIyIiwicHMiOiLikaBWMue+juilv2RtaXTmnoHlk4FH5Y+j4piAIiwiaWQiOiIzYzkxZDg1Ny0yZDQwLTM5YjktODFjMC1mNmFkZGU4MDM3ZmYifQ==",
	"vmess://eyJob3N0IjoicWxoazEuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL3YycmF5IiwidGxzIjoidGxzIiwiYWRkIjoicWxoazEuZG91YmxlZG91LndpbiIsInBvcnQiOjQ0MywiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKRoFYy6Zi/6YeM6aaZ5riv6L276YePMeKYgCIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0IjoicWxoazIuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL3YycmF5IiwidGxzIjoidGxzIiwiYWRkIjoicWxoazIuZG91YmxlZG91LndpbiIsInBvcnQiOjQ0MywiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKRoFYy6Zi/6YeM6aaZ5riv6L276YePMuKYgCIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0IjoicWxoazQuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL3YycmF5IiwidGxzIjoidGxzIiwiYWRkIjoicWxoazQuZG91YmxlZG91LndpbiIsInBvcnQiOjQ0MywiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKRoFYy6Zi/6YeM6aaZ5riv6L276YePNOKYgCIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0IjoicWxoazUuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL3YycmF5IiwidGxzIjoidGxzIiwiYWRkIjoicWxoazUuZG91YmxlZG91LndpbiIsInBvcnQiOjQ0MywiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKRoFYy6Zi/6YeM6aaZ5riv6L276YePNeKYgCIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0IjoiYXouZG91YmxlZG91LndpbiIsInBhdGgiOiJcL2RvdWRvdSIsInRscyI6InRscyIsImFkZCI6ImF6LmRvdWJsZWRvdS53aW4iLCJwb3J0IjoyMzM0MiwiYWlkIjowLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKRoFYy6aaZ5rivYXp1cmXimIAiLCJpZCI6IjNjOTFkODU3LTJkNDAtMzliOS04MWMwLWY2YWRkZTgwMzdmZiJ9",
	"vmess://eyJob3N0IjoiaGtiZ3AuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL2RvdWRvdSIsInRscyI6InRscyIsImFkZCI6Imh1bmFuLmRvdWJsZWRvdS53aW4iLCJwb3J0IjoyNTAwMiwiYWlkIjowLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKRoFYy6aaZ5rivYmdw55S15L+h6IGU6YCa5LyY5YyW4piAIiwiaWQiOiIzYzkxZDg1Ny0yZDQwLTM5YjktODFjMC1mNmFkZGU4MDM3ZmYifQ==",
	"vmess://eyJob3N0IjoiaGtiZ3AuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL2RvdWRvdSIsInRscyI6InRscyIsImFkZCI6ImhrYmdwLmRvdWJsZWRvdS53aW4iLCJwb3J0IjoyMzM0MiwiYWlkIjowLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKRoFYy6aaZ5rivYmdw56e75Yqo5LyY56eA4piAIiwiaWQiOiIzYzkxZDg1Ny0yZDQwLTM5YjktODFjMC1mNmFkZGU4MDM3ZmYifQ==",
	"vmess://eyJob3N0IjoiY21pLmRvdWJsZWRvdS53aW4iLCJwYXRoIjoiXC9kb3Vkb3UiLCJ0bHMiOiJ0bHMiLCJhZGQiOiJjbWkuZG91YmxlZG91LndpbiIsInBvcnQiOjQ1ODAsImFpZCI6MCwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsInYiOiIyIiwicHMiOiLikaBWMummmea4r0NNSeKYgCIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0IjoidjJkbWl0aGsuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL2RvdWRvdSIsInRscyI6InRscyIsImFkZCI6InYyZG1pdGhrLmRvdWJsZWRvdS53aW4iLCJwb3J0Ijo0NTYsImFpZCI6MiwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsInYiOiIyIiwicHMiOiLikaBWMummmea4r2RtaXQx4piAIiwiaWQiOiIzYzkxZDg1Ny0yZDQwLTM5YjktODFjMC1mNmFkZGU4MDM3ZmYifQ==",
	"vmess://eyJob3N0IjoidjJkbWl0aGsuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL2RvdWRvdSIsInRscyI6InRscyIsImFkZCI6InYyZG1pdGhrLmRvdWJsZWRvdS53aW4iLCJwb3J0Ijo0NTYsImFpZCI6MiwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsInYiOiIyIiwicHMiOiLikaBWMummmea4r2RtaXQx6LSf6L29MuKYgCIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0IjoidjJkbWl0aGszLmRvdWJsZWRvdS53aW4iLCJwYXRoIjoiXC9kb3Vkb3UiLCJ0bHMiOiJ0bHMiLCJhZGQiOiJ2MmRtaXRoazMuZG91YmxlZG91LndpbiIsInBvcnQiOjU2NywiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKRoFYy6aaZ5rivZG1pdDLimIAiLCJpZCI6IjNjOTFkODU3LTJkNDAtMzliOS04MWMwLWY2YWRkZTgwMzdmZiJ9",
	"vmess://eyJob3N0IjoiaGt0LmRvdWJsZWRvdS53aW4iLCJwYXRoIjoiXC9kb3Vkb3UiLCJ0bHMiOiJ0bHMiLCJhZGQiOiJoa3QuZG91YmxlZG91LndpbiIsInBvcnQiOjQ0MywiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKRoFYy6aaZ5rivSEtU4piAIiwiaWQiOiIzYzkxZDg1Ny0yZDQwLTM5YjktODFjMC1mNmFkZGU4MDM3ZmYifQ==",
	"vmess://eyJob3N0IjoiaGt0LmRvdWJsZWRvdS53aW4iLCJwYXRoIjoiXC9kb3Vkb3UiLCJ0bHMiOiJ0bHMiLCJhZGQiOiJnenlkLmRvdWJsZWRvdS53aW4iLCJwb3J0IjoyMzM0MSwiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKRoFYy6aaZ5rivSEtU55S15L+h5LyY5YyW4piAIiwiaWQiOiIzYzkxZDg1Ny0yZDQwLTM5YjktODFjMC1mNmFkZGU4MDM3ZmYifQ==",
	"vmess://eyJob3N0IjoidjJkbWl0aGsuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL2RvdWRvdSIsInRscyI6InRscyIsImFkZCI6ImhrdjYuZG91YmxlZG91LndpbiIsInBvcnQiOjQ1NiwiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKRoFYy6aaZ5rivSVBWNuKYgCIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0Ijoib25laGsyLmRvdWJsZWRvdS53aW4iLCJwYXRoIjoiXC9kb3Vkb3UiLCJ0bHMiOiJ0bHMiLCJhZGQiOiJnenlkLmRvdWJsZWRvdS53aW4iLCJwb3J0Ijo1MDAwNCwiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKRoFYy6aaZ5rivb25ldnBzMuKYgCIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0Ijoid3R0LmRvdWJsZWRvdS53aW4iLCJwYXRoIjoiXC9kb3Vkb3UiLCJ0bHMiOiJ0bHMiLCJhZGQiOiJ3dHQuZG91YmxlZG91LndpbiIsInBvcnQiOjQ1ODAsImFpZCI6MCwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsInYiOiIyIiwicHMiOiLikaBWMummmea4r1dUVOKYgCIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0Ijoid3R0LmRvdWJsZWRvdS53aW4iLCJwYXRoIjoiXC9kb3Vkb3UiLCJ0bHMiOiJ0bHMiLCJhZGQiOiJzaGFuZ2hhaS5kb3VibGVkb3Uud2luIiwicG9ydCI6NTAwMTAsImFpZCI6MCwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsInYiOiIyIiwicHMiOiLikaBWMummmea4r1dUVOenu+WKqOS8mOWMluKYgCIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0IjoidjJsb25kb24uZG91YmxlZG91LndpbiIsInBhdGgiOiJcL3YycmF5IiwidGxzIjoidGxzIiwiYWRkIjoidjJsb25kb24uZG91YmxlZG91LndpbiIsInBvcnQiOjQ0MywiYWlkIjozLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKTqlYy5Lym5pWmIiwiaWQiOiIzYzkxZDg1Ny0yZDQwLTM5YjktODFjMC1mNmFkZGU4MDM3ZmYifQ==",
	"vmess://eyJob3N0IjoiZ2VydjIuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL3YycmF5IiwidGxzIjoidGxzIiwiYWRkIjoiZ2VydjIuZG91YmxlZG91LndpbiIsInBvcnQiOjgwODAsImFpZCI6MiwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsInYiOiIyIiwicHMiOiLik6pWMuW+t+WbvSIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0IjoiZ2VydjIuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL3YycmF5IiwidGxzIjoidGxzIiwiYWRkIjoiZ2VydjYuZG91YmxlZG91LndpbiIsInBvcnQiOjgwODAsImFpZCI6MiwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsInYiOiIyIiwicHMiOiLik6pWMuW+t+WbvUlQVjYiLCJpZCI6IjNjOTFkODU3LTJkNDAtMzliOS04MWMwLWY2YWRkZTgwMzdmZiJ9",
	"vmess://eyJob3N0Ijoic3lkbmV5LmRvdWJsZWRvdS53aW4iLCJwYXRoIjoiXC9kb3Vkb3UiLCJ0bHMiOiJ0bHMiLCJhZGQiOiJzeWRuZXkuZG91YmxlZG91LndpbiIsInBvcnQiOjQ0MywiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKTqlYy5oKJ5bC8IiwiaWQiOiIzYzkxZDg1Ny0yZDQwLTM5YjktODFjMC1mNmFkZGU4MDM3ZmYifQ==",
	"vmess://eyJob3N0IjoidjJvbmVzZ3AuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL3YycmF5IiwidGxzIjoidGxzIiwiYWRkIjoidjJvbmVzZ3AuZG91YmxlZG91LndpbiIsInBvcnQiOjQ0MywiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKTqlYy5paw5Yqg5Z2hIiwiaWQiOiIzYzkxZDg1Ny0yZDQwLTM5YjktODFjMC1mNmFkZGU4MDM3ZmYifQ==",
	"vmess://eyJob3N0IjoidjJvbmVzZ3AuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL3YycmF5IiwidGxzIjoidGxzIiwiYWRkIjoic2dwdjYuZG91YmxlZG91LndpbiIsInBvcnQiOjQ0MywiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKTqlYy5paw5Yqg5Z2hSVBWNiIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0IjoidjJvbmVzZ3AuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL3YycmF5IiwidGxzIjoidGxzIiwiYWRkIjoidjJzZ3Bkby5kb3VibGVkb3Uud2luIiwicG9ydCI6NDQ1MCwiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKTqlYy5paw5Yqg5Z2h56e75Yqo5LyY5YyWIiwiaWQiOiIzYzkxZDg1Ny0yZDQwLTM5YjktODFjMC1mNmFkZGU4MDM3ZmYifQ==",
	"vmess://eyJob3N0IjoidjJpaWpqcDEuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL3YycmF5IiwidGxzIjoidGxzIiwiYWRkIjoidjJpaWpqcDEuZG91YmxlZG91LndpbiIsInBvcnQiOjgwLCJhaWQiOjIsIm5ldCI6IndzIiwidHlwZSI6Im5vbmUiLCJ2IjoiMiIsInBzIjoi4pOqVjLml6XmnKxvbmV2cHMxIiwiaWQiOiIzYzkxZDg1Ny0yZDQwLTM5YjktODFjMC1mNmFkZGU4MDM3ZmYifQ==",
	"vmess://eyJob3N0IjoidjJpaWpqcDIuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL3YycmF5IiwidGxzIjoidGxzIiwiYWRkIjoidjJpaWpqcDIuZG91YmxlZG91LndpbiIsInBvcnQiOjQ0MywiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKTqlYy5pel5pysb25ldnBzMiIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0IjoidjJpaWpqcDMuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL3YycmF5IiwidGxzIjoidGxzIiwiYWRkIjoidjJpaWpqcDMuZG91YmxlZG91LndpbiIsInBvcnQiOjgwLCJhaWQiOjQsIm5ldCI6IndzIiwidHlwZSI6Im5vbmUiLCJ2IjoiMiIsInBzIjoi4pOqVjLml6XmnKxvbmV2cHMzIiwiaWQiOiIzYzkxZDg1Ny0yZDQwLTM5YjktODFjMC1mNmFkZGU4MDM3ZmYifQ==",
	"vmess://eyJob3N0IjoidjJpaWpqcDYuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL2RvdWZlbiIsInRscyI6InRscyIsImFkZCI6InYyaWlqanA2LmRvdWJsZWRvdS53aW4iLCJwb3J0Ijo0NDMsImFpZCI6MiwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsInYiOiIyIiwicHMiOiLik6pWMuaXpeacrG9uZXZwczQiLCJpZCI6IjNjOTFkODU3LTJkNDAtMzliOS04MWMwLWY2YWRkZTgwMzdmZiJ9",
	"vmess://eyJob3N0IjoidjJpaWpqcDYuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL2RvdWZlbiIsInRscyI6InRscyIsImFkZCI6InNoYW5naGFpLmRvdWJsZWRvdS53aW4iLCJwb3J0IjoxMDA4MCwiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKTqlYy5pel5pysb25ldnBzNeeUteS/oeenu+WKqOS8mOWMliIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0IjoidjJpaWpqcDcuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL2RvdWZlbiIsInRscyI6InRscyIsImFkZCI6InYyaWlqanA3LmRvdWJsZWRvdS53aW4iLCJwb3J0Ijo0NDMsImFpZCI6MiwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsInYiOiIyIiwicHMiOiLik6pWMuaXpeacrG9uZXZwczYiLCJpZCI6IjNjOTFkODU3LTJkNDAtMzliOS04MWMwLWY2YWRkZTgwMzdmZiJ9",
	"vmess://eyJob3N0IjoidjJpaWpqcDcuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL2RvdWZlbiIsInRscyI6InRscyIsImFkZCI6InNoYW5naGFpLmRvdWJsZWRvdS53aW4iLCJwb3J0IjoyMDA0MywiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKTqlYy5pel5pysb25ldnBzN+eUteS/oeenu+WKqOS8mOWMliIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0IjoidjJpaWpqcDIuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL3YycmF5IiwidGxzIjoidGxzIiwiYWRkIjoic2hhbmdoYWkuZG91YmxlZG91LndpbiIsInBvcnQiOjUwMDA3LCJhaWQiOjIsIm5ldCI6IndzIiwidHlwZSI6Im5vbmUiLCJ2IjoiMiIsInBzIjoi4pOqVjLml6XmnKxvbmV2cHM455S15L+h56e75Yqo5LyY5YyWIiwiaWQiOiIzYzkxZDg1Ny0yZDQwLTM5YjktODFjMC1mNmFkZGU4MDM3ZmYifQ==",
	"vmess://eyJob3N0IjoicHIuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL2RvdWRvdSIsInRscyI6InRscyIsImFkZCI6InByLmRvdWJsZWRvdS53aW4iLCJwb3J0Ijo0NTYsImFpZCI6MiwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsInYiOiIyIiwicHMiOiLik6pWMue+juWbvea0m+adieeftiIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0IjoicHIuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL2RvdWRvdSIsInRscyI6InRscyIsImFkZCI6InNoYW5naGFpLmRvdWJsZWRvdS53aW4iLCJwb3J0Ijo1MDAwOCwiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKTqlYy576O5Zu95rSb5p2J55+25Lit6L2sIiwiaWQiOiIzYzkxZDg1Ny0yZDQwLTM5YjktODFjMC1mNmFkZGU4MDM3ZmYifQ==",
	"vmess://eyJob3N0IjoidjJvbmVsb3MxLmRvdWJsZWRvdS53aW4iLCJwYXRoIjoiXC92MnJheSIsInRscyI6InRscyIsImFkZCI6InYyb25lbG9zMS5kb3VibGVkb3Uud2luIiwicG9ydCI6NDQzLCJhaWQiOjIsIm5ldCI6IndzIiwidHlwZSI6Im5vbmUiLCJ2IjoiMiIsInBzIjoi4pOqVjLnvo7lm73nur3nuqYiLCJpZCI6IjNjOTFkODU3LTJkNDAtMzliOS04MWMwLWY2YWRkZTgwMzdmZiJ9",
	"vmess://eyJob3N0IjoidjJvbmVsb3MxLmRvdWJsZWRvdS53aW4iLCJwYXRoIjoiXC92MnJheSIsInRscyI6InRscyIsImFkZCI6InNoYW5naGFpLmRvdWJsZWRvdS53aW4iLCJwb3J0IjoyNTAwMSwiYWlkIjoyLCJuZXQiOiJ3cyIsInR5cGUiOiJub25lIiwidiI6IjIiLCJwcyI6IuKTqlYy576O5Zu957q957qm5Lit6L2sIiwiaWQiOiIzYzkxZDg1Ny0yZDQwLTM5YjktODFjMC1mNmFkZGU4MDM3ZmYifQ==",
	"vmess://eyJob3N0Ijoib25laGsuZG91YmxlZG91LndpbiIsInBhdGgiOiJcL2RvdWRvdSIsInRscyI6InRscyIsImFkZCI6Im9uZWhrLmRvdWJsZWRvdS53aW4iLCJwb3J0Ijo0NDMsImFpZCI6MiwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsInYiOiIyIiwicHMiOiLik6pWMummmea4ryIsImlkIjoiM2M5MWQ4NTctMmQ0MC0zOWI5LTgxYzAtZjZhZGRlODAzN2ZmIn0=",
	"vmess://eyJob3N0Ijoib25laGsuZG91bmFpLndvcmtlcnMuZGV2IiwicGF0aCI6IlwvZG91ZG91IiwidGxzIjoidGxzIiwiYWRkIjoiaWNvb2sudHciLCJwb3J0Ijo0NDMsImFpZCI6MiwibmV0Ijoid3MiLCJ0eXBlIjoibm9uZSIsInYiOiIyIiwicHMiOiLik6pWMummmea4r0NG5Lit6L2sIiwiaWQiOiIzYzkxZDg1Ny0yZDQwLTM5YjktODFjMC1mNmFkZGU4MDM3ZmYifQ==",
}
